var filterFloat=function(b){return/^(\-|\+)?([0-9]+(\.[0-9]+)?|Infinity)$/.test(b)?Number(b):NaN};$(function(){$(".collapser").click(hideToggler);$(".mailme").each(function(){txt=$(this).html().replace(/ at /,"@").replace(/ dot /g,".");$(this).replaceWith('<a href="mailto:'+txt+'">'+txt+"</a>")});$(".misbut").click(function(){$(".prmis").css("background-color","#FFD3D3")})});function adBlockDetected(){$("#fabanner").show()}var hh=0,tiop=!1;
$(function(){$.fn.raty.defaults.path="/img";$.fn.raty.defaults.half=!0;$.fn.raty.defaults.score=function(){return $(this).attr("data-score")};"undefined"!=typeof usedrops&&usedrops?($(".rgrams").hide(),$(".rdrops").show(),$(".drprml").show()):($(".rgrams").show(),$(".rdrops").hide(),$(".drprml").hide());$("#title").focus();$("#fladd,.ftext").autocomplete({source:"/flavors/ajax",change:function(){ga("send","event","Flavors","ChangeFlavor",$(this).val())},select:function(b,a){$("#"+b.target.id).val(a.item.name);
chName(b.target.id.substr(2));$("input:radio[name=fpvo"+b.target.id.substr(2)+"]").filter("[value="+a.item.pg_vg_other+"]").prop("checked",!0);$("#fw"+b.target.id.substr(2)).val(a.item.weight_per_ml);$("#f"+b.target.id.substr(2)).focus();return!1}});0<$(".ftext,#fladd").length&&$(".ftext,#fladd").each(function(){$(this).data("ui-autocomplete")._renderItem=function(b,a){append=""!=a.make?" - "+a.make:"";append+=' <abbr class="reccount" title="# recipes">('+a.no_recipes+")</abbr>";return $("<li>").append("<a>"+
a.display_name+" "+append+"</a>").appendTo(b)}});$("textarea").autogrow();$(".ric").each(function(){$(this).click(function(){var b=$(this).data("rid"),a="";$.ajax({url:"/recipe/getFlavors/",type:"post",dataType:"json",data:{id:b},success:function(f){var e='<table class="table table-condensed table-striped">';for(n in f)e+="<tr><td>"+f[n].name+'</td><td class="tdper">'+f[n].perc+"%</td></tr>";a=e+"</table><script>ga('send', 'pageview', '"+b+"');\x3c/script>";$("#ri"+b).tooltip({items:"#ri"+b,position:{of:"#rp"+
b,my:"left+8 top",at:"right center"},content:a});$("#ri"+b).tooltip("open");tiop=!0}})});$(this).mouseleave(function(){if(tiop){var b="#ri"+$(this).data("rid");$(b).tooltip("close");tiop=!1}})});var b=$("head"),a=function(){b.find("meta[name=viewport]").remove();b.prepend('<meta name="viewport" content="width=device-width, initial-scale=0.75, user-scalable=1" />')};if(navigator.userAgent.length&&/iPhone|iPad|iPod/i.test(navigator.userAgent))$("input[type=text]").on({touchstart:function(){b.find("meta[name=viewport]").remove();
b.prepend('<meta name="viewport" content="width=device-width, initial-scale=0.75, user-scalable=0" />')}}).on({touchend:function(){setTimeout(a,500)}})});
function addFlavor(){nflav++;cla=1==nflav%2?" highlight":"";$("#flavors").append('<div class="control-group"><div class="input-append"><input class="ftext" type="text" name="ft'+nflav+'" id="ft'+nflav+'" value="" placeholder="'+flavtxt+" "+nflav+'" onfocus="selName('+nflav+')" onkeyup="chName('+nflav+')" onblur="chName('+nflav+')"><div class="controls"><input class="rinp" type="text" id="f'+nflav+'" name="f'+nflav+'" onkeyup="calcRec()"><div class="add-on">%</div></div></div></div><div class="pgvgo"><label class="smlab"><input type="radio" name="fpvo'+
nflav+'" checked="checked" value="0" onclick="calcRec()">PG</label><label class="smlab"><input type="radio" name="fpvo'+nflav+'" value="1" onclick="calcRec()">VG</label><label class="smlab"><input type="radio" name="fpvo'+nflav+'" value="2" onclick="calcRec()">'+otherlab+'</label><input type="hidden" name="fw'+nflav+'" id="fw'+nflav+'" value=""></div><br>');$("#recflavor").append('<div class="recline'+cla+'"><div class="rlab" id="rfl'+nflav+'">'+flavtxt+" "+nflav+'</div><div class="runit" id="flu'+
nflav+'"></div>'+(usedrops?"":'<div class="rgrams" id="flg'+nflav+'"></div>')+(usedrops?'<div class="rdrops" id="fld'+nflav+'"></div>':"")+'<div class="rpercent" id="flp'+nflav+'"></div><br></div>');$("#ft"+nflav).autocomplete({source:"/flavors/ajax",change:function(){ga("send","event","Flavors","AddFlavor",$(this).val())},select:function(b,a){$("#"+b.target.id).val(a.item.name);chName(b.target.id.substr(2));$("input:radio[name=fpvo"+b.target.id.substr(2)+"]").filter("[value="+a.item.pg_vg_other+
"]").prop("checked",!0);$("#fw"+b.target.id.substr(2)).val(a.item.weight_per_ml);$("#f"+b.target.id.substr(2)).focus();return!1}}).focus().data("ui-autocomplete")._renderItem=function(b,a){append=""!=a.make?" - "+a.make:"";append+=' <abbr class="reccount" title="# recipes">('+a.no_recipes+")</abbr>";return $("<li>").append("<a"+(1==a.in_stash?' class="instash"':"")+">"+a.display_name+" "+append+"</a>").appendTo(b)}}
function shErr(b){$("#errmsg").html(b);$("#err").height($(window).height()).width($(window).width()).show()}function noErr(){$("#err").hide()}
function calcRec(b){var a=0<$("#maxvg:checked").length;a?($("#pglab").hide(),$(".vglab").hide()):($("#pglab").show(),$(".vglab").show());neg=0;tml=$("#res").val();tstr=$("#tstre").val();str=$("#nstr").val();str=0<str?str:1;$("#rnstr").html(str+" mg");wv=$("#wvpga").val();var d=0;0==wv?$("#rwvpga").hide():$("#rwvpga").show();"undefined"!=typeof b&&("pgg"==b?$("#vgg").val(100-$("#pgg").val()):"vgg"==b?$("#pgg").val(100-$("#vgg").val()):"nivg"==b?$("#nipg").val(100-$("#nivg").val()):"nipg"==b&&$("#nivg").val(100-
$("#nipg").val()));pg=$("#pgg").val();vg=$("#vgg").val();a&&(pg=100,vg=0);npg=$("#nipg").val();nvg=$("#nivg").val();dpml=$("#xdpml").val();tg=tp=td=tm=resml=0;nicml=Math.round(tstr/str*tml*100)/100;nicdrops=Math.ceil(nicml*dpml);nicgrams=Math.round(100*(npg/100*nicml*1.036+nvg/100*nicml*1.261))/100;nicper=Math.round(nicml/tml*1E4)/100;$("#rnicml").html(nicml);$("#rnicdr").html(nicdrops);$("#rnicg").html(nicgrams);$("#rnicper").html(nicper);resml+=nicml;tm+=nicml;td+=nicdrops;tp+=nicper;tg+=nicgrams;
d+=pr.nic*nicml;wvml=Math.round(wv/100*tml*100)/100;wvdrops=Math.ceil(wvml*dpml);wvgrams=Math.round(93.8*wvml)/100;wvper=Math.round(wvml/tml*1E4)/100;$("#rwvpgaml").html(wvml);$("#rwvpgadr").html(wvdrops);$("#rwvpgag").html(wvgrams);$("#rwvpgaper").html(wvper);resml+=wvml;tm+=wvml;td+=wvdrops;tp+=wvper;tg+=wvgrams;d+=pr.wvpga*wvml;fltot=foml=fvgml=fpgml=0;b=!1;for(i=1;i<=nflav;i++)if(fl=$("#f"+i).val(),!isNaN(fl)){flml=Math.round(fl/100*tml*1E3)/1E3;fltot+=flml;fldr=Math.ceil(flml*dpml);flper=Math.round(flml/
tml*1E4)/100;flml=Math.round(100*flml)/100;$("#flu"+i).html(flml);$("#fld"+i).html(fldr);$("#flp"+i).html(flper);resml+=flml;tm+=flml;td+=fldr;tp+=flper;rbv=$("input[name='fpvo"+i+"']:checked").val();var c=$("#fw"+i).val();0==rbv?(fpgml+=flml,fgadj=0!=c?c:1):1==rbv?(fvgml+=flml,fgadj=0!=c?c:1.16):(foml+=flml,fgadj=0!=c?c:.98);flg=Math.round(flml*fgadj*100)/100;tg+=flg;$("#flg"+i).html(flg);d+=0<$("#fw"+i).data("prml")?$("#fw"+i).data("prml")*flml:0;if(!$("#fw"+i).data("prml")||0<$("#fw"+i).data("prml")&&
0==$("#fw"+i).data("prml")*flml)b=!0}restml=tml-resml;xpgml=Math.round(100*(pg/100*(tml-wvml-foml)-npg/100*nicml-fpgml))/100;d+=pr.pg*xpgml;xpgdrop=Math.ceil(xpgml*dpml);xpggrams=Math.ceil(1.036*xpgml*100)/100;xpgper=Math.round(xpgml/tml*1E4)/100;0>xpgml&&(neg=1);0==xpgml?(xpgper=xpgdrop=0,$("#rpgd").hide()):$("#rpgd").show();xvgml=Math.round(100*(vg/100*(tml-wvml-foml)-nvg/100*nicml-fvgml))/100;d+=pr.vg*xvgml;xvgdrop=Math.ceil(xvgml*dpml);xvggrams=Math.ceil(126.1*xvgml)/100;xvgper=Math.round(xvgml/
tml*1E4)/100;a&&(d-=pr.pg*xpgml,d+=pr.vg*xpgml,xvgml=Math.round(100*(xpgml+xvgml))/100,xvgdrop=Math.ceil(xvgml*dpml),xvggrams=Math.ceil(126.1*xvgml)/100,xvgper=Math.round(xvgml/tml*1E3)/10,xpgper=xpggrams=xpgdrop=xpgml=0,$("#rpgd").hide());0>xvgml&&(neg=1);0==xvgml?(xvgper=xpvdrop=0,$("#rvgd").hide()):$("#rvgd").show();tm+=xpgml+xvgml;td+=xpgdrop+xvgdrop;tp+=xpgper+xvgper;tg+=xpggrams+xvggrams;$("#rpgml").html(xpgml);$("#rpgdr").html(xpgdrop);$("#rpgg").html(xpggrams);$("#rpgper").html(xpgper);$("#rvgml").html(xvgml);
$("#rvgg").html(xvggrams);$("#rvgdr").html(xvgdrop);$("#rvgper").html(xvgper);$("#rtu").html(Math.round(100*tm)/100);$("#rtg").html(Math.round(100*tg)/100);$("#rtd").html(td);$("#fstr").html(Math.round(nicml/tm*str*10)/10);tvg=nvg/100*nicml+fvgml+xvgml;tpg=npg/100*nicml+fpgml+xpgml;vgr=Math.round(100*tvg/(tvg+tpg));pgr=Math.round(100*tpg/(tvg+tpg));$("#pvr").html(pgr+"/"+vgr);$("#rtp").html(Math.round(tp));theprice=d.toFixed(2);$("#pri").html(theprice);b?$("#warnpri").show():$("#warnpri").hide();
"0.00"==theprice&&$("shpri").hide();var f=1;$(".recline:visible").each(function(){f++;0==f%2?$(this).addClass("highlight"):$(this).removeClass("highlight")});1==neg?($("#ermsg").html(neg_val_error).show("fast"),$("#savebtn").attr("disabled","disabled")):($("#ermsg").hide("fast"),$("#savebtn").removeAttr("disabled"));100==npg?$("#nirat").html(npg+"% PG"):100==nvg?$("#nirat").html(nvg+"% VG"):$("#nirat").html(npg+"/"+nvg+" PG/VG");$("#flml").html(Math.round(100*fltot)/100+" ml");$("#flper").html(Math.round(1E4*
fltot/tml)/100+"%");$("#dpml").html(dpml);$("#bn").width(Math.round(nicper)+"%");$("#bp").width(Math.round(xpgper)+"%");$("#bv").width(Math.round(xvgper)+"%");$("#bf").width(100-(Math.round(nicper)+Math.round(xpgper)+Math.round(xvgper))+"%");a=parseFloat($("#rnicml").html());d=parseFloat($("#rnicdr").html());b=parseFloat($("#rnicg").html());c=parseFloat($("#rnicper").html());0<$("#rpgml:visible").length&&(a+=parseFloat($("#rpgml").html()),d+=parseFloat($("#rpgdr").html()),b+=parseFloat($("#rpgg").html()),
c+=parseFloat($("#rpgper").html()));0<$("#rvgml:visible").length&&(a+=parseFloat($("#rvgml").html()),d+=parseFloat($("#rvgdr").html()),b+=parseFloat($("#rvgg").html()),c+=parseFloat($("#rvgper").html()));0<$("#rvwpgaml:visible").length&&(a+=parseFloat($("#rvwpgaml").html()),d+=parseFloat($("#rvwpgadr").html()),b+=parseFloat($("#rvwpgag").html()),c+=parseFloat($("#rvwpgaper").html()));$("#totbaseml").html(Math.round(100*a)/100);$("#totbasedr").html(Math.round(100*d)/100);$("#totbaseg").html(Math.round(100*
b)/100);$("#totbaseper").html(Math.round(100*c)/100)}function chName(b){$("#rfl"+b).html($("#ft"+b).val())}function doNotes(){$("#rnotes").html($("#notes").val().replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g,"$1<br>$2"))}function rName(){$("#rname").text($("<div/>").html($("#title").val()).html())}function selName(b){$("#ft"+b).val()==flavtxt+" "+b&&$("#ft"+b).select()}
function chkFrm(){if(loggedin)return $("#title").val()==recnamedef||""==$.trim($("#title").val())?(alert(change_def_name),!1):!0;alert(not_logged_in_msg);return!1}
(function(b){b.fn.autogrow=function(a){this.filter("textarea").each(function(){var a=b(this),c=a.height();a.css("lineHeight");var f=b("<div></div>").css({position:"absolute",top:-1E4,left:-1E4,width:b(this).width()-parseInt(a.css("paddingLeft"))-parseInt(a.css("paddingRight"))-3,fontSize:a.css("fontSize"),fontFamily:a.css("fontFamily"),lineHeight:a.css("lineHeight"),resize:"none"}).appendTo(document.body),a=function(){var a=this.value.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/&/g,"&amp;").replace(/\n$/,
"<br/>&nbsp;").replace(/\n/g,"<br/>").replace(/ {2,}/g,function(a){for(var b=0,c="";b<a.length-1;b++)c+="&nbsp;";return c+" "});f.html(a);b(this).css("height",Math.max(f.height()+20,c))};b(this).change(a).keyup(a).keydown(a);a.apply(this)});return this}})(jQuery);function doFav(b){$.post("/favorite",{makefav:b},function(a){$("#favicon").attr("src","/img/heart"+a+".png");ga("send","event","Favorite","AddFavorite",$("#title").val());$("#favmenutext").text(1==a?favmenulinkrem:favmenulinkadd)})}
function chkCmt(){(ok=0<$("#cmt").val().length)||alert(no_comment_msg);ga("send","event","Comment","Recipe",$("#title").val());return ok}function doEdit(b){$("#acttext").html(edit_text);ga("send","event","Recipe","Edit",$("#title").val());$("#orgid").val(b);$("#frmrec").show("fast");$("#baseon").hide();$("#title").focus()}
function showRecEdit(){$("#acttext").html(adapt_text);$("#orgid").val("");$("#ispriv").prop("checked",!0);$("#frmrec").show("fast");$("#baseon").hide();$("#title").focus();$("#byuser").html(by_you);$("#grav").attr("src","http://www.gravatar.com/avatar/"+mygrav+"?d=http%3A%2F%2Fe-liquid-recipes.com%2Fimg%2Favatar_40.png&s=40");$("#res").val(mdef.res);$("#tstre").val(mdef.tstre);$("#wvpga").val(mdef.wvpga);$("#pgg").val(mdef.pgg);$("#vgg").val(mdef.vgg);$("#nstr").val(mdef.nstr);$("#nipg").val(mdef.nipg);
$("#nivg").val(mdef.nivg);$("#xdpml").val(mdef.xdpml);calcRec();ga("send","event","Recipe","Adapt",$("#title").val())}function adjFlavor(){$("#frmrec").is(":visible")?(newperc=prompt("Adjust total flavor percentage",parseFloat($("#flper").html().substr(0,$("#flper").html().length-1))),newperc=parseFloat(newperc),isNaN(newperc)||adjCalc(newperc)):(doEdit(recid),setTimeout("adjFlavor()",400));return!1}
function adjCalc(b){var a=$("#flper").html().substr(0,$("#flper").html().length-1);b/=a;for(i=1;i<=nflav;i++)fl=filterFloat($("#f"+i).val()),$("#f"+i).val(Math.round(fl*b*100)/100);calcRec()}
function copyReddit(b){if(b=b?1==b:!1)var a="**["+$("#rname").text()+" (base)]("+window.location.href+")**\r\n\r\n",a=a+"Ingredient|ml|g|%\r\n:---|---:|---:|---:\r\n";else a="**["+$("#rname").text()+"]("+window.location.href+")**\r\n\r\n",a+="Ingredient|%\r\n:---|---:\r\n";for(i=1;i<=nflav;i++)fl=filterFloat($("#flp"+i).text()),isNaN(fl)||(a=b?a+($("#rfl"+i).text().trim()+"|"+$("#flu"+i).text()+"|"+$("#flg"+i).text()+"|"+$("#flp"+i).text()+"\r\n"):a+($("#rfl"+i).text().trim()+"|"+$("#flp"+i).text()+
"\r\n"));b?(a+="\r\nTotal base: "+$("#res").val()+" ml  \r\n",a+="To be mixed at: "+$("#tperc").text()+"%  \r\n",a+="This is enough for "+$("#tmix").text()+" ml of finished liquid.  \r\n"):a+="\r\nFlavor total: "+$("#flper").text()+"\r\n\r\n";return a+="Remember to rate it at [e-liquid-recipes.com!]("+window.location.href+")\r\n\r\n"}
function copyBbcode(b){if(b=b?1==b:!1)var a='[SIZE=3][url="'+window.location.href+'"]'+$("#rname").text()+" (base)[/URL][/SIZE]\r\n\r\n",a=a+"[TABLE][TR][TH]Ingredient[/TH][TH]ml[/TH][TH]g[/TH][TH]%[/TH][/TR]\r\n";else a='[SIZE=3][url="'+$("#short").val()+'"]'+$("#rname").text()+"[/URL][/SIZE]\r\n\r\n",a+="[TABLE][TR][TH]Ingredient[/TH][TH]%[/TH][/TR]\r\n";for(i=1;i<=nflav;i++)fl=filterFloat($("#flp"+i).text()),isNaN(fl)||(a=b?a+("[TR][TD]"+$("#rfl"+i).text().trim()+"[/TD][TD]"+$("#flu"+i).text()+
"[/TD][TD]"+$("#flg"+i).text()+"[/TD][TD]"+$("#flp"+i).text()+"[/TD][/TR]\r\n"):a+("[TR][TD]"+$("#rfl"+i).text().trim()+"[/TD][TD]"+$("#flp"+i).text()+"[/TD][/TR]\r\n"));b?(a=a+"[/TABLE]\r\n\r\n"+("Total base: "+$("#res").val()+" ml\r\n"),a+="To be mixed at: "+$("#tperc").text()+"%\r\n",a+="This is enough for "+$("#tmix").text()+" ml of finished liquid.\r\n",a+='Remember to rate it at [URL="'+window.location.href+'"]e-liquid-recipes.com![/URL]\r\n\r\n'):(a+="[/TABLE]\r\n\r\nFlavor total: "+$("#flper").text()+
"\r\n\r\n",a+='Remember to rate it at [URL="'+$("#short").val()+'"]e-liquid-recipes.com![/URL]\r\n\r\n');return a}
function copyHtml(b){var a=(b=b?1==b:!1)?'<h2><a href="'+window.location.href+'">'+$("#rname").text()+" (base)</a></h2>\r\n":'<h2><a href="'+$("#short").val()+'">'+$("#rname").text()+"</a></h2>\r\n",a=b?a+"<table><tr><th>Ingredient</th><th>ml</th><th>g</th><th>%</th></tr>\r\n":a+"<table><tr><th>Ingredient</th><th>%</th></tr>\r\n";for(i=1;i<=nflav;i++)fl=filterFloat($("#flp"+i).text()),isNaN(fl)||(a=b?a+("<tr><td>"+$("#rfl"+i).text().trim()+"</td><td>"+$("#flu"+i).text()+"</td><td>"+$("#flg"+i).text()+
"</td><td>"+$("#flp"+i).text()+"</td></tr>\r\n"):a+("<tr><td>"+$("#rfl"+i).text().trim()+"</td><td>"+$("#flp"+i).text()+"</td></tr>\r\n"));b?(a=a+"</table><br>"+("Total base: "+$("#res").val()+" ml<br>"),a+="To be mixed at: "+$("#tperc").text()+"%<br>",a+="This is enough for "+$("#tmix").text()+" ml of finished liquid.<br>",a+='Remember to rate it at <a href="'+window.location.href+'">e-liquid-recipes.com!</a>\r\n\r\n'):(a+="</table><br>Flavor total: "+$("#flper").text()+"<br><br>",a+='Remember to rate it at <a href="'+
$("#short").val()+'">e-liquid-recipes.com!</a>\r\n\r\n');return a}
function copySimple(b){var a=(b=b?1==b:!1)?$("#rname").text()+" (base): "+window.location.href+"\r\n\r\n":$("#rname").text()+": "+window.location.href+"\r\n\r\n";for(i=1;i<=nflav;i++)fl=filterFloat($("#flp"+i).text()),isNaN(fl)||(a+=" "+$("#flp"+i).text()+"% "+$("#rfl"+i).text()+"   \r\n");b?(a+="\r\n\r\nTotal base: "+$("#res").val()+" ml\r\n",a+="To be mixed at: "+$("#tperc").text()+"%\r\n",a+="Remember to rate it at: "+window.location.href+"\r\n\r\n"):(a+="\r\nFlavor total: "+$("#flper").text()+
"\r\n",a+="Remember to rate it at: "+$("#short").val()+"\r\n\r\n");return a}
function calcBase(b){var a=0,d=$("#res").val(),c,f,e,g=0,l=0,m=0;for(i=1;i<=nflav;i++)h=parseFloat($("#flu"+i).data("perc")),isNaN(h)||(a+=h);if(!0!==b){if($("#finper").val()<a){$("#tfper").html(a);$("#fal").show();return}if($("#finper").val()==a)$("#recpg").hide();else{var h=Math.round(100*($("#finper").val()-a))/100,a=$("#finper").val();c=Math.round(h/a*d*100)/100;f=Math.round(100*c)/100;e=filterFloat($("#flwper").val());$("#flupg").text(f);$("#flgpg").text(Math.round(f*e*100)/100);$("#flppg").text(Math.round(c/
d*1E4)/100);0==nflav%2&&$("#recpg").addClass("highlight");$("#recpg").show()}}$("#fal").hide();for(i=1;i<=nflav;i++)h=parseFloat($("#flu"+i).data("perc")),isNaN(h)||(c=Math.round(h/a*d*100)/100,f=Math.round(100*c)/100,e=filterFloat($("#flw"+i).val()),isNaN(e)&&(e=1,"1"==$("#dt"+i).text()?e=1.16:"2"==$("#dt"+i).text()&&(e=.98)),$("#flu"+i).text(f),$("#flg"+i).text(Math.round(f*e*100)/100),$("#flp"+i).text(Math.round(c/d*1E4)/100),g+=h/a*d,l+=h/a*d*e,m+=h/a*d/d);$("#tperc").text(Math.round(100*a)/100);
$("#tmix").text(Math.round(d/a*100));$("#totml").text(Math.round(100*g)/100);$("#totg").text(Math.round(100*l)/100);$("#totp").text(Math.round(1E4*m)/100);!0===b&&$("#finper").val(Math.round(100*a)/100)}function saveFlavorBaseDef(b){parseInt(b)&&$.post(window.location.href,{ml:b})}function handleMaxVG(){calcRec()}
function hideToggler(){var b=$(this);$(this).nextAll().each(function(){var a=$(this);if(!$(this).hasClass("collapsible")){if(!$(this).children().first().hasClass("collapsible"))return!1;a=$(this).children().first()}a.slideToggle("fast",function(){b.children("i[class*=chevron]").remove();b.append(' <i class="icon icon-chevron-'+($(this).is(":visible")?"down":"right")+'"></i>')})})}
(function(b){var a=!1;"function"===typeof define&&define.amd&&(define(b),a=!0);"object"===typeof exports&&(module.exports=b(),a=!0);if(!a){var d=window.Cookies,c=window.Cookies=b();c.noConflict=function(){window.Cookies=d;return c}}})(function(){function b(){for(var a=0,b={};a<arguments.length;a++){var f=arguments[a],e;for(e in f)b[e]=f[e]}return b}function a(d){function c(a,e,g){var l;if("undefined"!==typeof document){if(1<arguments.length){g=b({path:"/"},c.defaults,g);if("number"===typeof g.expires){var m=
new Date;m.setMilliseconds(m.getMilliseconds()+864E5*g.expires);g.expires=m}try{l=JSON.stringify(e),/^[\{\[]/.test(l)&&(e=l)}catch(r){}e=d.write?d.write(e,a):encodeURIComponent(String(e)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent);a=encodeURIComponent(String(a));a=a.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);a=a.replace(/[\(\)]/g,escape);return document.cookie=[a,"=",e,g.expires?"; expires="+g.expires.toUTCString():"",g.path?"; path="+g.path:
"",g.domain?"; domain="+g.domain:"",g.secure?"; secure":""].join("")}a||(l={});for(var m=document.cookie?document.cookie.split("; "):[],h=/(%[0-9A-Z]{2})+/g,q=0;q<m.length;q++){var t=m[q].split("="),k=t.slice(1).join("=");'"'===k.charAt(0)&&(k=k.slice(1,-1));try{var p=t[0].replace(h,decodeURIComponent),k=d.read?d.read(k,p):d(k,p)||k.replace(h,decodeURIComponent);if(this.json)try{k=JSON.parse(k)}catch(r){}if(a===p){l=k;break}a||(l[p]=k)}catch(r){}}return l}}c.set=c;c.get=function(a){return c.call(c,
a)};c.getJSON=function(){return c.apply({json:!0},[].slice.call(arguments))};c.defaults={};c.remove=function(a,d){c(a,"",b(d,{expires:-1}))};c.withConverter=a;return c}return a(function(){})});function toglSize(){var b;b=Cookies.get("txtsize")?Cookies.get("txtsize"):$("body").css("font-size");"14px"==b?b="16px":"16px"==b?b="18px":"18px"==b&&(b="14px");Cookies.set("txtsize",b,{expires:365,path:"/"});$("body").css("font-size",b);return!1}
$(function(){Cookies.get("txtsize")&&$("body").css("font-size",Cookies.get("txtsize"))});function disgo(b){$("#loader").show();window.location.href=b;return!1};
